from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from .database import Base

class YarnSupplier(Base):
    __tablename__ = 'yarn_and_supplier_database'

    Material_No = Column(Integer, primary_key=True, index=True)
    Bulk = Column(Float)
    Dev = Column(Integer)
    Descripion = Column(String)  # Matching typo in Excel
    Type = Column(String)
    Supplier = Column(String)
    Price = Column(Float)
    Material_Type = Column('Material Type', String)
    Special = Column(String)
    Ply = Column(Integer)
    Count_dtex = Column('Count (dtex)', Integer)
    Full_Count = Column('Full Count', Integer)
    Filaments = Column(Float)
    Lustre = Column(String)
    Fully_drawn_Textured = Column('Fully drawn/ Textured (FDY/DTY)', String)
    TPM = Column(Float)
    PPM = Column(Float)
    DTEX_Count = Column('DTEX Count   - (ASTMD1907) ', Float)
    Hot_Water_Shrinkage = Column('Hot Water Shrinkage (%)(ASTMD 2259)', Float)
    Back_Twist = Column(Float)
    Linear_Denesity = Column('Linear Denesity (Tex)', Float)
    Brecking_Tenacity = Column('Brecking Tenacity (cN/tex)', Float)
    Tensile_Strength = Column('Tensile Strength (N)', Float)
    Elongation = Column('Elongation (%)      (EN ISO 2062)', Float)
    CF_To_Rubbing = Column('C/F To Rubbing', Float)
    CF_To_Washing = Column('C/F To Washing', Float)
    CF_To_Water = Column('C/F To Water', Float)
    CF_To_Acid = Column('C/F To Acid', Float)
    Country = Column(String)
    Incoterm = Column(String)
    SF_Cost = Column('SF Cost (USD)', Float)
    AF_Cost = Column('AF Cost(USD)', Float)
    SF_Landed_Cost = Column('SF Landed Cost (USD)', Float)
    AF_Landed_Cost = Column('AF Landed Cost(USD)', Float)
    Manufacture_LT = Column('Manufacture LT(Week)', String)
    MOQ = Column('MOQ(Kg)', String)
    Supplier_Count = Column('Supplier Count (Dtex)', Float)
    Supplier_Tenacity = Column('Supplier Tenacity', Float)
    Supplier_Elongation = Column('Supplier Elongation', Float)
    Suplier_Shrinkage = Column('Suplier Shrinkage', Float) # Matching typo in Excel
    Supplier_Intermingling = Column('Supplier Intermingling', Float)
    Supplier_Twist_Per_Metre = Column('Supplier Twist Per Metre', Float)
    Supplier_Oil_Content = Column('Supplier Oil Content', Float)
    
    # Relationship with design database
    designs = relationship("DesignDatabase", back_populates="yarn")

class DesignDatabase(Base):
    __tablename__ = 'design_database'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    Yarn_Code_Technologist = Column('Yarn Code (Technologist)', Integer, ForeignKey('yarn_and_supplier_database.Material_No'))
    Sketch_Number = Column('Sketch Number', Float)
    Proposing_Method = Column('Proposing Method', String)
    Production = Column(String)
    Construction = Column(String)
    Sketcher = Column(Float)
    Yarn_Recycle = Column('Yarn Recycle/ Regular', Float)
    Lace_Status = Column('Lace Status (100% recycle/ 50% recycle/ Regular)', String)
    Project = Column(Float)
    Customer = Column(String)
    Finish_Quality = Column('Finish Quality', Integer)
    Lace_Type = Column('Lace Type', String)
    Weft_Elasticity = Column('Weft Elasticity', Float)
    Warp_Elasticity = Column('Warp Elasticity', Float)
    Moulding = Column(String)
    Clipping = Column(String)
    Cut_out = Column('Cut-out', String)
    Scalloping = Column(String)
    Draw_code = Column('Draw code', String)
    Lycra_Back = Column('Lycra Back', String)
    Thermo_yarn_path = Column('Thermo yarn path', Float)
    Right_Left_Panels = Column('Right & Left Panels', Float)
    Code_Modified = Column('Code Modified', Float)
    Nb_Courses = Column('Nb Courses', Integer)
    Nb_courses_between_2_pillar_locks = Column('Nb courses between 2 pillar locks', Float)
    Repeat_Length = Column('Repeat Length (mm)', Integer)
    Repeat_width = Column('Repeat width (mm)', Integer)
    Gauge = Column(Integer)
    Needle_set_up = Column('Needle set up', Integer)
    Nb_of_bars = Column('Nb of bars', Integer)
    Nb_of_Bands = Column('Nb of Bands', Integer)
    Nb_of_racks = Column('Nb of racks\n', Integer)
    Nb_of_repeats = Column('Nb of repeats', Integer)
    Designer_comments = Column('Designer comments', Float)
    Nature = Column(String)
    Yarn_code_Designer = Column('Yarn code (Designer)', Float)
    Description_Designer = Column('Description (Designer)', Float)
    Article_Number = Column('Article Number', String, index=True)
    Description_Technologist = Column('Description (Technologist)', String)
    Pilot_Status = Column('Pilot Status', String)
    Yarn_consumption = Column('Yarn consumption %', Float)
    Yield = Column(String)
    Stretch_Warp = Column('Stretch (Warp)', Float)
    Stretch_Weft = Column('Stretch (Weft)', Float)
    Bursting_Strength = Column('Bursting Strength ', String)
    
    # Relationship back to yarn
    yarn = relationship("YarnSupplier", back_populates="designs")

class YarnCombination(Base):
    __tablename__ = 'yarn_combinations'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    Item = Column(String)
    Article_No = Column('Article No/ Customer Ref', String)
    Sketch_No = Column('Sketch No', String)
    Yarn_1 = Column('Yarn 1', Integer, ForeignKey('yarn_and_supplier_database.Material_No'))
    Yarn_2 = Column('Yarn 2', Integer, ForeignKey('yarn_and_supplier_database.Material_No'))
    Yarn_3 = Column('Yarn 3', Integer, ForeignKey('yarn_and_supplier_database.Material_No'))
    Yarn_4 = Column('Yarn 4', Integer, ForeignKey('yarn_and_supplier_database.Material_No'))
    Yarn_5 = Column('Yarn 5', Integer, ForeignKey('yarn_and_supplier_database.Material_No'))
    Yarn_6 = Column('Yarn 6', Integer, ForeignKey('yarn_and_supplier_database.Material_No'))
    Yarn_7 = Column('Yarn 7', Integer, ForeignKey('yarn_and_supplier_database.Material_No'))
    Yarn_8 = Column('Yarn 8', Integer, ForeignKey('yarn_and_supplier_database.Material_No'))
    Yarn_9 = Column('Yarn 9', Integer, ForeignKey('yarn_and_supplier_database.Material_No'))
    Yarn_10 = Column('Yarn 10', Integer, ForeignKey('yarn_and_supplier_database.Material_No'))
    Yarn_11 = Column('Yarn 11', Integer, ForeignKey('yarn_and_supplier_database.Material_No'))
    Comments = Column(String)

class SourcingConstraint(Base):
    __tablename__ = 'sourcing_constraints'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    constraint_type = Column(String, nullable=False)
    target_value = Column(String, nullable=False)
    scope = Column(String, nullable=False)
    action = Column(String, nullable=False) # "boost" or "hard_restrict"
    weight = Column(Float, nullable=True)
    priority = Column(Integer, nullable=True)
    start_date = Column(DateTime, nullable=True)
    end_date = Column(DateTime, nullable=True)
    reason = Column(String, nullable=True)
    set_by = Column(String, nullable=True)
    active = Column(Boolean, nullable=False, default=True)
